export const pagesRoutes = [
  ["v-184f4da6","/intro.html",{"y":"p","t":"关于我","i":"aboutme"},["/intro","/intro.md"]],
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"discovery"},["/index.html","/README.md"]],
  ["v-2e25198a","/database/",{"y":"p","t":"数据库","i":"database"},["/database/index.html","/database/README.md"]],
  ["v-7d72c4ac","/framework/",{"y":"p","t":"框架","i":"framework"},["/framework/index.html","/framework/README.md"]],
  ["v-14b0a7d7","/home/",{"y":"p","t":"欢迎","i":"daohang"},["/home/index.html","/home/README.md"]],
  ["v-71b3ae87","/interview/",{"y":"p","t":"面经","i":"interview"},["/interview/index.html","/interview/README.md"]],
  ["v-14c69af4","/java/",{"y":"p","t":"Java","i":"java"},["/java/index.html","/java/README.md"]],
  ["v-7273d1ac","/middleware/1nginx.html",{"d":1684043545000,"c":["中间件"],"g":["Nginx","中间件"],"r":{"minutes":0.04,"words":13},"y":"a","t":"Nginx","i":"nginx"},["/middleware/1nginx","/middleware/1nginx.md"]],
  ["v-d8f9caa6","/middleware/2rabbitmq.html",{"d":1684043545000,"c":["中间件"],"g":["Nginx","中间件"],"r":{"minutes":0.04,"words":13},"y":"a","t":"RabbitMq","i":"rabbitmq"},["/middleware/2rabbitmq","/middleware/2rabbitmq.md"]],
  ["v-4d194044","/middleware/",{"y":"p","t":"中间件","i":"middleware"},["/middleware/index.html","/middleware/README.md"]],
  ["v-15054f24","/note/",{"y":"p","t":"笔记","i":"note"},["/note/index.html","/note/README.md"]],
  ["v-5e93fa4a","/photo/99%E5%B9%B3%E6%BD%AD.html",{"d":1683896623000,"c":["摄影"],"g":["平潭","旅拍"],"e":"<h3> 2023年四月</h3>\n<p><img src=\"https://blog-1312634242.cos.ap-shanghai.myqcloud.com/2023/05/08/19982315297a4559bc67e8b0c6e0a979.png\" alt=\"image.png\">\n去年八月去平潭看海，大太阳晒的掉皮，不过风景是真滴好看\n对于特别喜欢看海的人不会放过每一次机会，于是今年四月我又来平潭了。</p>\n","r":{"minutes":0.83,"words":248},"y":"a","t":"平潭四月","i":"picture"},["/photo/99平潭.html","/photo/99%E5%B9%B3%E6%BD%AD","/photo/99平潭.md","/photo/99%E5%B9%B3%E6%BD%AD.md"]],
  ["v-e2acc714","/photo/",{"y":"p","t":"拍拍","i":"photo"},["/photo/index.html","/photo/README.md"]],
  ["v-c91da0ba","/database/1mysql/",{"y":"p","t":"Mysql","i":"mysql"},["/database/1mysql/index.html","/database/1mysql/README.md"]],
  ["v-50823daa","/database/2redis/",{"y":"p","t":"Redis","i":"redis"},["/database/2redis/index.html","/database/2redis/README.md"]],
  ["v-182fabca","/framework/1spring/",{"y":"p","t":"Spring","i":"spring"},["/framework/1spring/index.html","/framework/1spring/README.md"]],
  ["v-e26068d4","/java/1java/1java.html",{"d":1684043545000,"c":["Java"],"g":["Java基础","八股"],"e":"<div class=\"hint-container info\">\n<p class=\"hint-container-title\">相关信息</p>\n<p>知识点来自B站黑马程序员</p>\n</div>\n\n<div class=\"language-text line-numbers-mode\" data-ext=\"text\"><pre class=\"language-text\"><code>java测试代码\n</code></pre><div class=\"line-numbers\" aria-hidden=\"true\"><div class=\"line-number\"></div></div></div>","r":{"minutes":0.21,"words":63},"y":"a","t":"Java基础(上)","i":"page"},["/java/1java/1java","/java/1java/1java.md"]],
  ["v-2cfca4b0","/java/1java/",{"y":"p","t":"Java基础","i":"javabasic"},["/java/1java/index.html","/java/1java/README.md"]],
  ["v-649aac6c","/java/2jvm/",{"y":"p","t":"JVM","i":"jvm"},["/java/2jvm/index.html","/java/2jvm/README.md"]],
  ["v-64a8bef6","/java/3juc/",{"y":"p","t":"JUC","i":"juc"},["/java/3juc/index.html","/java/3juc/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},["/404"]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类"},["/category/index.html"]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签"},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章"},["/article/index.html"]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏"},["/star/index.html"]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴"},["/timeline/index.html"]],
  ["v-9d681cea","/category/%E4%B8%AD%E9%97%B4%E4%BB%B6/",{"y":"p","t":"中间件 分类"},["/category/中间件/","/category/%E4%B8%AD%E9%97%B4%E4%BB%B6/index.html"]],
  ["v-1a8900ba","/tag/nginx/",{"y":"p","t":"Nginx 标签"},["/tag/nginx/index.html"]],
  ["v-0a768c4f","/category/%E6%91%84%E5%BD%B1/",{"y":"p","t":"摄影 分类"},["/category/摄影/","/category/%E6%91%84%E5%BD%B1/index.html"]],
  ["v-7876eec1","/tag/%E4%B8%AD%E9%97%B4%E4%BB%B6/",{"y":"p","t":"中间件 标签"},["/tag/中间件/","/tag/%E4%B8%AD%E9%97%B4%E4%BB%B6/index.html"]],
  ["v-5831b135","/category/java/",{"y":"p","t":"Java 分类"},["/category/java/index.html"]],
  ["v-3b45d3f9","/tag/%E5%B9%B3%E6%BD%AD/",{"y":"p","t":"平潭 标签"},["/tag/平潭/","/tag/%E5%B9%B3%E6%BD%AD/index.html"]],
  ["v-6b298b3e","/tag/%E6%97%85%E6%8B%8D/",{"y":"p","t":"旅拍 标签"},["/tag/旅拍/","/tag/%E6%97%85%E6%8B%8D/index.html"]],
  ["v-68cf5b32","/tag/java%E5%9F%BA%E7%A1%80/",{"y":"p","t":"Java基础 标签"},["/tag/java基础/","/tag/java%E5%9F%BA%E7%A1%80/index.html"]],
  ["v-beb4d5e8","/tag/%E5%85%AB%E8%82%A1/",{"y":"p","t":"八股 标签"},["/tag/八股/","/tag/%E5%85%AB%E8%82%A1/index.html"]],
]
