export const pagesRoutes = [
  ["v-184f4da6","/intro.html",{"v":"https://blog-1312634242.cos.ap-shanghai.myqcloud.com/2023/aboutme.jpg","e":"<h1> 关于我</h1>\n<p>杭州某电专计算机专业研二学生</p>\n<p>日常狗混子，摸鱼王者</p>\n","r":{"minutes":0.12,"words":35},"y":"a","t":"关于我","i":"aboutme"},["/intro","/intro.md"]],
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"home"},["/index.html","/README.md"]],
  ["v-14b0a7d7","/home/",{"v":"https://blog-1312634242.cos.ap-shanghai.myqcloud.com/2023/indexbg.jpg","e":"<h3> 快速导航</h3>\n<ul>\n<li><a href=\"/java\">Java</a></li>\n<li><a href=\"/database\">数据库</a></li>\n<li><a href=\"/framework\">框架</a></li>\n<li><a href=\"/note\">学习笔记</a></li>\n<li><a href=\"/interview\">面经</a></li>\n<li><a href=\"/interview\">随处拍拍</a></li>\n<li><a href=\"/intro.html\" target=\"blank\">关于我</a></li>\n</ul>\n","r":{"minutes":0.17,"words":50},"y":"a","t":"欢迎来到我的空间","i":"discover"},["/home/index.html","/home/README.md"]],
  ["v-4b0d24f4","/java/%E5%9F%BA%E7%A1%80/java.html",{"c":["Java"],"r":{"minutes":0.03,"words":10},"y":"a","t":"Java基础","i":"page"},["/java/基础/java.html","/java/%E5%9F%BA%E7%A1%80/java","/java/基础/java.md","/java/%E5%9F%BA%E7%A1%80/java.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},["/404"]],
  ["v-1194f663","/java/%E5%9F%BA%E7%A1%80/",{"y":"p","t":"基础"},["/java/基础/","/java/%E5%9F%BA%E7%A1%80/index.html"]],
  ["v-14c69af4","/java/",{"y":"p","t":"Java"},["/java/index.html"]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类"},["/category/index.html"]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签"},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章"},["/article/index.html"]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏"},["/star/index.html"]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴"},["/timeline/index.html"]],
  ["v-5831b135","/category/java/",{"y":"p","t":"Java 分类"},["/category/java/index.html"]],
]
