export const pagesRoutes = [
  ["v-184f4da6","/intro.html",{"y":"p","t":"关于我","i":"aboutme"},["/intro","/intro.md"]],
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"discovery"},["/index.html","/README.md"]],
  ["v-2e25198a","/database/",{"y":"p","t":"数据库","i":"database","I":0},["/database/index.html","/database/README.md"]],
  ["v-7d72c4ac","/framework/",{"y":"p","t":"框架","i":"framework","I":0},["/framework/index.html","/framework/README.md"]],
  ["v-14b0a7d7","/home/",{"y":"p","t":"欢迎","i":"daohang","I":0},["/home/index.html","/home/README.md"]],
  ["v-71b3ae87","/interview/",{"y":"p","t":"面经","i":"interview","I":0},["/interview/index.html","/interview/README.md"]],
  ["v-14c69af4","/java/",{"y":"p","t":"Java","i":"java","I":0},["/java/index.html","/java/README.md"]],
  ["v-7273d1ac","/middleware/1nginx.html",{"d":1684043545000,"c":["中间件"],"g":["Nginx","中间件"],"r":{"minutes":0.04,"words":13},"y":"a","t":"Nginx","i":"nginx"},["/middleware/1nginx","/middleware/1nginx.md"]],
  ["v-d8f9caa6","/middleware/2rabbitmq.html",{"d":1684043545000,"c":["中间件"],"g":["RabbitMq","中间件"],"r":{"minutes":0.04,"words":13},"y":"a","t":"RabbitMq","i":"rabbitmq"},["/middleware/2rabbitmq","/middleware/2rabbitmq.md"]],
  ["v-4d194044","/middleware/",{"y":"p","t":"中间件","i":"middleware","I":0},["/middleware/index.html","/middleware/README.md"]],
  ["v-15054f24","/note/",{"y":"p","t":"笔记","i":"note","I":0},["/note/index.html","/note/README.md"]],
  ["v-5e93fa4a","/photo/99%E5%B9%B3%E6%BD%AD.html",{"d":1683896623000,"c":["摄影"],"g":["平潭","旅拍"],"e":"<h3> 2023年四月</h3>\n<p><img src=\"https://blog-1312634242.cos.ap-shanghai.myqcloud.com/2023/05/08/19982315297a4559bc67e8b0c6e0a979.png\" alt=\"image.png\">\n去年八月去平潭看海，大太阳晒的掉皮，不过风景是真滴好看\n对于特别喜欢看海的人不会放过每一次机会，于是今年四月我又来平潭了。</p>\n","r":{"minutes":0.83,"words":248},"y":"a","t":"平潭四月","i":"picture"},["/photo/99平潭.html","/photo/99%E5%B9%B3%E6%BD%AD","/photo/99平潭.md","/photo/99%E5%B9%B3%E6%BD%AD.md"]],
  ["v-e2acc714","/photo/",{"y":"p","t":"拍拍","i":"photo","I":0},["/photo/index.html","/photo/README.md"]],
  ["v-c91da0ba","/database/1mysql/",{"y":"p","t":"Mysql","i":"mysql","I":0},["/database/1mysql/index.html","/database/1mysql/README.md"]],
  ["v-50823daa","/database/2redis/",{"y":"p","t":"Redis","i":"redis","I":0},["/database/2redis/index.html","/database/2redis/README.md"]],
  ["v-182fabca","/framework/1spring/",{"y":"p","t":"Spring","i":"spring","I":0},["/framework/1spring/index.html","/framework/1spring/README.md"]],
  ["v-e26068d4","/java/1java/1java.html",{"d":1684043545000,"c":["Java"],"g":["Java基础","八股"],"e":"<div class=\"hint-container tip\">\n<p class=\"hint-container-title\">梦开始的地方</p>\n<p>一切就从这里开始吧</p>\n</div>\n<h2> JVM  JRE  JDK</h2>\n<p>JVM是java虚拟机，针对不同系统有不同的实现，常用的为HotSpot VM。</p>\n<p>JDK是功能齐全的SDK，包含JRE和一些其他的工具，例如javac，java等。</p>\n<p>JRE是Java运行时环境，仅包含Java应用程序运行时的必要环境。</p>\n","r":{"minutes":5.31,"words":1592},"y":"a","t":"Java基础一","i":"page"},["/java/1java/1java","/java/1java/1java.md"]],
  ["v-f9cd8696","/java/1java/2java.html",{"d":1684077684000,"c":["Java"],"g":["Java基础","八股"],"e":"<h2> 面向对象</h2>\n<h3> 面向对象和面向过程的区别</h3>\n<ul>\n<li>面向过程把解决问题的过程拆成一个个方法，通过一个个方法的执行解决问题。</li>\n<li>面向对象会先抽象出对象，然后用对象执行方法的方式解决问题。</li>\n</ul>\n<p>一个注重过程，一个注重内部属性。</p>\n","r":{"minutes":9.37,"words":2810},"y":"a","t":"Java基础二","i":"page"},["/java/1java/2java","/java/1java/2java.md"]],
  ["v-49079e4a","/java/1java/3reflex.html",{"d":1684147588000,"c":["Java"],"g":["Java反射","八股"],"e":"<h2> 反射</h2>\n<p>反射可以获取任意一个类的所有属性和方法，还能调用这些方法和属性。</p>\n","r":{"minutes":1.28,"words":383},"y":"a","t":"Java反射","i":"page"},["/java/1java/3reflex","/java/1java/3reflex.md"]],
  ["v-63b48971","/java/1java/4javaProxy.html",{"d":1684147588000,"c":["Java"],"g":["代理模式","八股"],"e":"<h2> 代理模式</h2>\n<p>使用代理对象来代替真实对象的访问，这样能在不改变目标对象的前提下，提供额外的功能，扩展目标对象。</p>\n<p>代理模式有静态代理和动态代理两种实现方式。</p>\n","r":{"minutes":4.4,"words":1320},"y":"a","t":"代理模式","i":"page"},["/java/1java/4javaProxy","/java/1java/4javaProxy.md"]],
  ["v-a94b071a","/java/1java/5singleton.html",{"d":1684159018000,"c":["Java"],"g":["单例模式","八股"],"e":"<h2> 单例模式</h2>\n<p>保证在整个系统中，对某一个类只会存在一个对象实例，并且类只提供一个取得对象实例的方法。</p>\n","r":{"minutes":1.77,"words":530},"y":"a","t":"单例模式","i":"page"},["/java/1java/5singleton","/java/1java/5singleton.md"]],
  ["v-2cfca4b0","/java/1java/",{"y":"p","t":"Java基础","i":"javabasic","I":0},["/java/1java/index.html","/java/1java/README.md"]],
  ["v-32f3b57d","/java/2collection/1collection.html",{"d":1684217915000,"c":["Java"],"g":["Java集合","八股"],"e":"<h2> 集合</h2>\n<p>Java集合由两大接口派生而来，分别是用来存放单一元素的<code>Collection</code>和用来存放键值对的<code>Map</code>接口。对于<code>Collection</code>接口有三个子接口，分别是<code>List</code>、<code>Set</code>、<code>Queue</code>。</p>\n","r":{"minutes":4.93,"words":1478},"y":"a","t":"Java集合一","i":"page"},["/java/2collection/1collection","/java/2collection/1collection.md"]],
  ["v-1485935c","/java/2collection/2collection.html",{"d":1684222203000,"c":["Java"],"g":["Java集合","八股"],"e":"<h2> Map</h2>\n<h3> HashMap 和 Hashtable 的区别</h3>\n<ul>\n<li><strong>线程是否安全</strong>：<code>HashMap</code>是非线程安全的，<code>Hashtable</code>是线程安全的，内部方法使用<code>synchronized</code>修饰。</li>\n<li><strong>效率</strong>：因为锁的问题，<code>HashMap</code>的效率要稍微好点。</li>\n<li><strong>是否能存储Null Key和Value</strong>：<code>HashMap</code>能存储<code>null</code>的key和value，但是作为<code>null</code>的key只能有一个，<code>Hashtable</code>不能有<code>null</code>key和value。</li>\n<li><strong>扩容</strong>：<code>Hashtable</code>默认初始大小是11，扩容之后变为2n+1。<code>HashMap</code>默认大小是16，每次扩容变为原来的两倍。</li>\n<li><strong>底层</strong>：JDK1.8之后<code>HashMap</code>底层使用数组+链表/红黑树，特定条件链表转化为红黑树，<code>Hashtable</code>则没有转化为红黑树的机制。</li>\n</ul>\n","r":{"minutes":3.99,"words":1197},"y":"a","t":"Java集合二","i":"page"},["/java/2collection/2collection","/java/2collection/2collection.md"]],
  ["v-31c43ed3","/java/2collection/",{"y":"p","t":"集合","i":"jihe","I":0},["/java/2collection/index.html","/java/2collection/README.md"]],
  ["v-64a8bef6","/java/3juc/",{"y":"p","t":"并发编程","i":"juc","I":0},["/java/3juc/index.html","/java/3juc/README.md"]],
  ["v-64b6db6e","/java/4jvm/",{"y":"p","t":"JVM","i":"jvm","I":0},["/java/4jvm/index.html","/java/4jvm/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},["/404"]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类","I":0},["/category/index.html"]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签","I":0},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章","I":0},["/article/index.html"]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏","I":0},["/star/index.html"]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴","I":0},["/timeline/index.html"]],
  ["v-9d681cea","/category/%E4%B8%AD%E9%97%B4%E4%BB%B6/",{"y":"p","t":"中间件 分类","I":0},["/category/中间件/","/category/%E4%B8%AD%E9%97%B4%E4%BB%B6/index.html"]],
  ["v-1a8900ba","/tag/nginx/",{"y":"p","t":"Nginx 标签","I":0},["/tag/nginx/index.html"]],
  ["v-0a768c4f","/category/%E6%91%84%E5%BD%B1/",{"y":"p","t":"摄影 分类","I":0},["/category/摄影/","/category/%E6%91%84%E5%BD%B1/index.html"]],
  ["v-7876eec1","/tag/%E4%B8%AD%E9%97%B4%E4%BB%B6/",{"y":"p","t":"中间件 标签","I":0},["/tag/中间件/","/tag/%E4%B8%AD%E9%97%B4%E4%BB%B6/index.html"]],
  ["v-5831b135","/category/java/",{"y":"p","t":"Java 分类","I":0},["/category/java/index.html"]],
  ["v-63bcc623","/tag/rabbitmq/",{"y":"p","t":"RabbitMq 标签","I":0},["/tag/rabbitmq/index.html"]],
  ["v-3b45d3f9","/tag/%E5%B9%B3%E6%BD%AD/",{"y":"p","t":"平潭 标签","I":0},["/tag/平潭/","/tag/%E5%B9%B3%E6%BD%AD/index.html"]],
  ["v-6b298b3e","/tag/%E6%97%85%E6%8B%8D/",{"y":"p","t":"旅拍 标签","I":0},["/tag/旅拍/","/tag/%E6%97%85%E6%8B%8D/index.html"]],
  ["v-68cf5b32","/tag/java%E5%9F%BA%E7%A1%80/",{"y":"p","t":"Java基础 标签","I":0},["/tag/java基础/","/tag/java%E5%9F%BA%E7%A1%80/index.html"]],
  ["v-beb4d5e8","/tag/%E5%85%AB%E8%82%A1/",{"y":"p","t":"八股 标签","I":0},["/tag/八股/","/tag/%E5%85%AB%E8%82%A1/index.html"]],
  ["v-155ef28f","/tag/java%E5%8F%8D%E5%B0%84/",{"y":"p","t":"Java反射 标签","I":0},["/tag/java反射/","/tag/java%E5%8F%8D%E5%B0%84/index.html"]],
  ["v-f7b9fed4","/tag/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F/",{"y":"p","t":"代理模式 标签","I":0},["/tag/代理模式/","/tag/%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F/index.html"]],
  ["v-2652ff58","/tag/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F/",{"y":"p","t":"单例模式 标签","I":0},["/tag/单例模式/","/tag/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F/index.html"]],
  ["v-12e56aa2","/tag/java%E9%9B%86%E5%90%88/",{"y":"p","t":"Java集合 标签","I":0},["/tag/java集合/","/tag/java%E9%9B%86%E5%90%88/index.html"]],
]
